### ISSUE TITLE
Add function comment

### ISSUE THREAD

**Issue by GabrielLacoste** [merces/showcomments#2]
Hi, I added to yours showcomments project to show the function comment and a column with the function name of the comment. How I can give the code to you? I try to make a branch but got an access denied,

**Comment by merces** [comment]
Hi @GabrielLacoste. That's great, thanks! You can fork this repository, make the changes, commit to your fork and then open a PR. This way Github will list you as a contributor to this project. However, if you don't have time to learn how things work on Github, or you just lack the interest, you can paste your code here and we can discuss. ;)
